[opener]
office = [
    { run = 'flatpak run org.onlyoffice.desktopeditors "$@"', orphan = true, for = "linux" },
]

[open]
prepend_rules = [
    { url = "*.docx", use = "office" },
    { url = "*.docm", use = "office" },
    { url = "*.dotx", use = "office" },
    { url = "*.dotm", use = "office" },
    { url = "*.doc",  use = "office" },
    { url = "*.dot",  use = "office" },
    { url = "*.rtf",  use = "office" },
    { url = "*.xlsx",  use = "office" },
    { url = "*.xlsm",  use = "office" },
    { url = "*.xlsb",  use = "office" },
    { url = "*.xltm",  use = "office" },
    { url = "*.xltx",  use = "office" },
    { url = "*.xls",   use = "office" },
    { url = "*.xlt",   use = "office" },
    { url = "*.pptx",  use = "office" },
    { url = "*.pptm",  use = "office" },
    { url = "*.ppsx",  use = "office" },
    { url = "*.ppsm",  use = "office" },
    { url = "*.potx",  use = "office" },
    { url = "*.potm",  use = "office" },
    { url = "*.ppt",   use = "office" },
    { url = "*.pps",   use = "office" },
    { url = "*.pot",   use = "office" },
    { url = "*.odt",  use = "office" },
    { url = "*.ods",  use = "office" },
    { url = "*.odp",  use = "office" },
    { url = "*.odg",  use = "office" },
    { url = "*.odf",  use = "office" },
]

[plugin]
prepend_preloaders = [
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*",            run = "office" },
    { mime = "application/msword",        run = "office" },
    { mime = "application/msexcel",       run = "office" },
    { mime = "application/mspowerpoint",  run = "office" },
    { mime = "application/rtf",           run = "office" },
]

prepend_previewers = [
    { url = "*.docx",  run = "office" },
    { url = "*.docm",  run = "office" },
    { url = "*.dotx",  run = "office" },
    { url = "*.dotm",  run = "office" },
    { url = "*.doc",   run = "office" },
    { url = "*.dot",   run = "office" },
    { url = "*.xlsx",  run = "office" },
    { url = "*.xlsm",  run = "office" },
    { url = "*.xlsb",  run = "office" },
    { url = "*.xltm",  run = "office" },
    { url = "*.xltx",  run = "office" },
    { url = "*.xls",   run = "office" },
    { url = "*.xlt",   run = "office" },
    { url = "*.pptx",  run = "office" },
    { url = "*.pptm",  run = "office" },
    { url = "*.ppsx",  run = "office" },
    { url = "*.ppsm",  run = "office" },
    { url = "*.potx",  run = "office" },
    { url = "*.potm",  run = "office" },
    { url = "*.ppt",   run = "office" },
    { url = "*.pps",   run = "office" },
    { url = "*.pot",   run = "office" },
    { url = "*.odt",   run = "office" },
    { url = "*.ods",   run = "office" },
    { url = "*.odp",   run = "office" },
    { url = "*.odg",   run = "office" },
    { url = "*.odf",   run = "office" },
    { url = "*.rtf",   run = "office" },
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*",            run = "office" },
    { mime = "application/msword",        run = "office" },
    { mime = "application/msexcel",       run = "office" },
    { mime = "application/mspowerpoint",  run = "office" },
    { mime = "application/rtf",           run = "office" },
]
